### ISSUE TITLE
Problem with webpage responsiveness

### ISSUE THREAD

**Issue by huy2272** [jainammshah12/6amigos-soen341projectF2023#15]
I've had a look at the recent changes in the pull request, and here are a few observations and suggestions:

Login Button : I noticed the login button isn't clickable anymore.
Navigation Bar : There is problem with the navbar movement. Besides that, well done with the logo

**Comment by Zineb2a** [comment]
I've fixed the login problem. ( We should have added pointer: cursor ) And for the Nav Bar it's all good ( change position to relative not absolute )
